[process]
price = 50000
default_days_for_prescription = 3

[theme]
font_size = 12

main_frame = [206, 219, 186]
patient_info = [230, 239, 254]
visit_info = [230, 239, 254]
order_info = [230, 239, 254]
